insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A01', 'TV');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A02', 'Coffe/Tea Maker');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A03', 'Heater');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A04', 'Irons');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A05', 'Air Conditioner');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A06', 'Internet Access');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A07', 'Washing Machine');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A08', 'Kitchen');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A09', 'Refrigerator');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A10', 'Bathtub');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A11', 'Balcony/Terrace');
insert into ROOM_AMENITIES (AmenityID, AmenityName) values ('A12', 'Pets allowed in room');
