insert into FACILITIES (FacilityID, FacilityName) values ('F01', 'Swimming Pool');
insert into FACILITIES (FacilityID, FacilityName) values ('F02', 'Airport Transfer');
insert into FACILITIES (FacilityID, FacilityName) values ('F03', 'Family/Child Friendly');
insert into FACILITIES (FacilityID, FacilityName) values ('F04', 'Restaurants');
insert into FACILITIES (FacilityID, FacilityName) values ('F05', 'Night Club');
insert into FACILITIES (FacilityID, FacilityName) values ('F06', 'Golf Course');
insert into FACILITIES (FacilityID, FacilityName) values ('F07', 'Gym');
insert into FACILITIES (FacilityID, FacilityName) values ('F08', 'Car park');
insert into FACILITIES (FacilityID, FacilityName) values ('F09', 'Sauna/Spa');
insert into FACILITIES (FacilityID, FacilityName) values ('F10', 'Facilities for disabled guests');
